version: '1'
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8097:8097"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@fullstack3_high?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=ADMIN
      - spring.datasource.password=OracleCloud12321
      - cors.allowed-origins=http://localhost:4200,http://184.73.143.68:4200
    restart: always